Traceback (most recent call last):
  File "/public/home/acr0vd9ik6/project/DiT/fast-DiT/test_py/test.py", line 21, in <module>
    from models_original import DiT_models
ModuleNotFoundError: No module named 'models_original'
